### ISSUE TITLE
is the default can be used for prediction

### ISSUE THREAD

**Issue by MPurushothamRao** [drgoulet/Codon-optimization#2]
When i ran rnn_predict.py script always predicted sequence, when convert back to protein. the predicted protein does not corresponds to original protein sequence.
or should i just train it again to get a new model

**Comment by drgoulet** [comment]
Yes, the default model should work for predicting hamster DNA sequence -- you shouldn't need to retrain the model. When tested, the output DNA sequence always back-translated to the correct protein sequence. 

- Can you share the protein sequence you're trying to optimize, or some properties such as length and whether it has any non-natural amino acids? 
- How wrong is the output? Are a few amino acids wrong, or is the sequence mostly wrong?

**Comment by MPurushothamRao** [comment]
Sorry, i ran the rnn_train.py with less number of sequences that is the reason the amino acids outputted were wrong now that i ran without any training the output is correct. 
Thank You for the clarification
